version: '3.8'

services:
  db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: devdb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
